name: Build and Deploy Laravel Static

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout الكود
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - run: npm install

      # 4️⃣ Build assets
      - run: npm run build

      # Prepare files for deployment
      - name: Prepare files
        run: |
          cp public/index.html public/404.html
          cp -r public/build/* public/
          cp public/.htaccess public/build/

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          force_orphan: true
#