name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, pdo
          coverage: xdebug

      # 3️⃣ Copy .env
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # 4️⃣ Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 5️⃣ Generate app key
      - name: Generate key
        run: php artisan key:generate

      # 6️⃣ Set permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # 7️⃣ Install NPM dependencies & build assets
      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      # 8️⃣ Prepare SQLite database
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # 9️⃣ Run tests
      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit --coverage-text

      # 🔟 Optional: Deploy to GitHub Pages or server
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
